version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: user-api
    restart: always
    build: .
    ports: 
      - "4000:4000"
    depends_on:
      - db
